export enum LineStateType {
  NONE = "NONE",
  CHANGELOG_TITLE = "CHANGELOG_TITLE",
  CHANGELOG_DATE = "CHANGELOG_DATE",
  DESCRIPTION_TEXT = "DESCRIPTION_TEXT",
  DESCRIPTION_BULLET = "DESCRIPTION_BULLET",
}
